app = "templar"
primary_region = "dfw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[deploy]
strategy = "rolling"

[env]
PORT = "41641"

[[services]]
protocol = "udp"
internal_port = 41641

[[services.ports]]
port = 41641
